### ISSUE TITLE
mrtransform: [ERROR] unknown option "-reorient_fod"

### ISSUE THREAD

**Issue by caojiezhang** [MASILab/STrUDeL#1]
I met an issue about mrtransform that does not have the option "-reorient_fod". Is it about the version of mrtransform? Do you have another alternative way?

**Comment by KarthikMasi** [comment]
We are using the following version of mrtrix
    git clone https://github.com/MRtrix3/mrtrix3.git
    cd mrtrix3
    git checkout 3.0.3

We have the singularity recipe shared here:

https://github.com/MASILab/cornn_tractography/blob/master/Singularity
